/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package storehausimport;

import entity.Firmas;
import entity.Klienti;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static jdk.nashorn.internal.objects.NativeString.substring;
/**
 *
 * @author Kaspars
 */
public class CompanieForImport extends javax.swing.JFrame {

    /**
     * Creates new form CompanieForImport
     */
    public EntityManager selectedCompanyEntityManager=null;
    public entity.Firmas companieForImport=null;
    public entity.Klienti selectedCompanyData=null;
    private String serverHost;
    private String serverPort;
    private String serverUser;
    private String serverPassword;

    public Object getSelectedCompanyData() {
        return selectedCompanyData;
    }


    public CompanieForImport() {
        initComponents();
    }

    public javax.swing.JTextField jtextSelectedCompany = null;

    public void setJtextSelectedCompany(JTextField jtextSelectedCompany) {
        this.jtextSelectedCompany = jtextSelectedCompany;
    }

      
    public void setcompanieForImport(Firmas companieForImport) {
        this.companieForImport = companieForImport;
    }

    public Firmas getcompanieForImport() {
        return companieForImport;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        try{
            serverHost=mainFrame.readGralsIni("sql", "server");
            serverPort=mainFrame.readGralsIni("sql", "port");
            serverUser=mainFrame.readGralsIni("sql", "uid");
            serverPassword=mainFrame.readGralsIni("sql", "password");

            if (serverHost.isEmpty()){
                throw new Exception("Neizdevās noslīt no Grals.ini mainigo:server");
            }
            if (serverPort.isEmpty()){
                throw new Exception("Neizdevās noslīt no Grals.ini mainigo:port");
            }
            if (serverUser.isEmpty()){
                throw new Exception("Neizdevās noslīt no Grals.ini mainigo:uid");
            }
            if (serverPassword.isEmpty()){
                throw new Exception("Neizdevās noslīt no Grals.ini mainigo:password");
            }

            Map propertiesGralsDB = new HashMap();
            propertiesGralsDB.put("javax.persistence.jdbc.url", "jdbc:postgresql://"+serverHost+":"+serverPort+"/grals");
            propertiesGralsDB.put("javax.persistence.jdbc.user", serverUser);
            propertiesGralsDB.put("javax.persistence.jdbc.driver", "org.postgresql.Driver");
            propertiesGralsDB.put("javax.persistence.jdbc.password", serverPassword);
            gralsEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("storeHausImportPU",propertiesGralsDB).createEntityManager();
            firmasQuery = java.beans.Beans.isDesignTime() ? null : gralsEntityManager.createQuery("SELECT f FROM Firmas f order by f.nosaukums");
            firmasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : firmasQuery.getResultList();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTableListOfCompany = new javax.swing.JTable(){;
                private static final long serialVersionUID = 1L;
                public boolean isCellEditable(int row, int column) {
                    return false;
                };
            };
            buttonClose = new javax.swing.JButton();
            buttonAcept = new javax.swing.JButton();

        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Kļūda pieslēdzoties datu bāzei! "+e.getMessage());
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izvēlieties firmu, kurā importēsiet dokumentus");
        setName("frameListOfCompanie"); // NOI18N
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jTableListOfCompany.setColumnSelectionAllowed(true);
        jTableListOfCompany.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableListOfCompany.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, firmasList, jTableListOfCompany, "JtableListOfCompany");
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nosaukums}"));
        columnBinding.setColumnName("Nosaukums");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${paskaidroj}"));
        columnBinding.setColumnName("Paskaidrojums");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTableListOfCompany.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTableListOfCompanyMouseMoved(evt);
            }
        });
        jTableListOfCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListOfCompanyMouseClicked(evt);
            }
        });
        jTableListOfCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableListOfCompanyKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListOfCompany);
        jTableListOfCompany.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        buttonClose.setText("Aizvērt");
        buttonClose.setToolTipText("Aizvērt logu, atlikt darbību");
        buttonClose.setPreferredSize(new java.awt.Dimension(85, 23));
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        buttonAcept.setText("Apstiprināt");
        buttonAcept.setMaximumSize(new java.awt.Dimension(67, 23));
        buttonAcept.setMinimumSize(new java.awt.Dimension(67, 23));
        buttonAcept.setPreferredSize(new java.awt.Dimension(67, 23));
        buttonAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAcept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void jTableListOfCompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListOfCompanyKeyPressed
        // TODO add your handling code here: 
        if (evt.getKeyCode () == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
        
    }//GEN-LAST:event_jTableListOfCompanyKeyPressed

    private void buttonAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptActionPerformed
        try {
            // TODO add your handling code here:
            this.aceptCompanyChoose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Kļūda: "+ex.getMessage());
        }
    }//GEN-LAST:event_buttonAceptActionPerformed

    private void jTableListOfCompanyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListOfCompanyMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableListOfCompanyMouseMoved

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formFocusLost

    private void jTableListOfCompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListOfCompanyMouseClicked
        // TODO add your handling code here:
       if (evt.getClickCount() == 2){
           try {
               this.aceptCompanyChoose();
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(null,"Kļūda: "+ex.getMessage());
           }
       }
    }//GEN-LAST:event_jTableListOfCompanyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanieForImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanieForImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanieForImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanieForImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new CompanieForImport().setVisible(true);
                
            }
        });
    }
    
    private void aceptCompanyChoose() throws Exception{
        int[] selected = jTableListOfCompany.getSelectedRows();
        if (selected.length>1){
            JOptionPane.showMessageDialog(null,"Izvēlieties tikai vienu firmu, kurā importēsiet dokumentus!");
            return;
        }
        entity.Firmas companieForImport =  firmasList.get(jTableListOfCompany.convertRowIndexToModel(selected[0]));

        try {
            serverHost=mainFrame.readGralsIni("sql", "server");
            serverPort=mainFrame.readGralsIni("sql", "port");
            serverUser=mainFrame.readGralsIni("sql", "uid");
            serverPassword=mainFrame.readGralsIni("sql", "password");
        } catch (Exception  ex)  {
            throw new Exception(ex.getMessage());
        }
        if (serverHost.isEmpty()){
            throw new Exception("Neizdevās noslīt no Grals.ini mainigo:server");
        }
        if (serverPort.isEmpty()){
            throw new Exception("Neizdevās noslīt no Grals.ini mainigo:port");
        }
        if (serverUser.isEmpty()){
            throw new Exception("Neizdevās noslīt no Grals.ini mainigo:uid");
        }
        if (serverPassword.isEmpty()){
            throw new Exception("Neizdevās noslīt no Grals.ini mainigo:password");
        }
        
        Map properties = new HashMap();
        properties.put("javax.persistence.jdbc.url", "jdbc:postgresql://"+serverHost+":"+serverPort+"/"+companieForImport.getFirma());
        properties.put("javax.persistence.jdbc.user", serverUser);
        properties.put("javax.persistence.jdbc.driver", "org.postgresql.Driver");
        properties.put("javax.persistence.jdbc.password", serverPassword);
//        properties.put("javax.persistence.jdbc.url", "jdbc:postgresql://localhost:5432/"+companieForImport.getFirma());
//        properties.put("javax.persistence.jdbc.user", "postgres");
//        properties.put("javax.persistence.jdbc.driver", "org.postgresql.Driver");
//        properties.put("javax.persistence.jdbc.password", "1");

//        properties.put("javax.persistence.jdbc.url", "jdbc:postgresql://192.168.11.11:5432/"+companieForImport.getFirma());
//        properties.put("javax.persistence.jdbc.user", "grals");
//        properties.put("javax.persistence.jdbc.driver", "org.postgresql.Driver");
//        properties.put("javax.persistence.jdbc.password", "79ENwAjUpXxls3Dh6RXo");
        try {
            selectedCompanyEntityManager=javax.persistence.Persistence.createEntityManagerFactory("selectedCompanyPU", properties).createEntityManager();
        } catch (PersistenceException  ex)  {
            throw new Exception(ex.getMessage());
        }

        if (this.jtextSelectedCompany!=null && selectedCompanyEntityManager!=null){
            try {
                try {
                    selectedCompanyData=(Klienti) selectedCompanyEntityManager.createNamedQuery("Klienti.findByKlients")
                            .setParameter("klients",substring(companieForImport.getNosaukums(),0,companieForImport.getNosaukums().indexOf(",")))
                            .getSingleResult();
                            
                } catch (Exception  ex)  {
                    JOptionPane.showMessageDialog(null,"Datu bāzes pieslēguma pārbaude nav izdevusies!\n"+companieForImport.getNosaukums()+
                    " datu bāze ("+companieForImport.getFirma()+")\n"+ex.getMessage());
                }
                
                
            } catch (PersistenceException  ex)  {
                JOptionPane.showMessageDialog(null,"Neizdevās pieslēgties pie "+companieForImport.getNosaukums()+
                " datu bāzes ("+companieForImport.getFirma()+")\n"+ex.getMessage());
                 if (selectedCompanyEntityManager.getTransaction().isActive())
                    selectedCompanyEntityManager.getTransaction().rollback();   
                  selectedCompanyEntityManager.close();
                                           
            }
            if (selectedCompanyData.equals(null)){
                selectedCompanyEntityManager=null;
            } else{
                storehausimport.mainFrame.setCompanyEntityManager(selectedCompanyEntityManager);
                storehausimport.mainFrame.setSelectedCompanyData(selectedCompanyData);
                jtextSelectedCompany.setText(companieForImport.getNosaukums());
                storehausimport.mainFrame.addToLog("Izvēlēta firma: "+companieForImport.getNosaukums()+" datu importēšanai.");
            }
 
        }
        
        this.setVisible(false);
    }            
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcept;
    private javax.swing.JButton buttonClose;
    private java.util.List<entity.Firmas> firmasList;
    private javax.persistence.Query firmasQuery;
    public javax.persistence.EntityManager gralsEntityManager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListOfCompany;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
